import pygame

class Star_Background:
    def __init__(self, screen):
        self.screen = screen
        self.star_bg_width = screen.get_width() * 3
        self.star_bg_surf = pygame.Surface((self.star_bg_width, screen.get_height()), pygame.SRCALPHA)

        self.sm_px = 2

        self.star_color_bright = (250, 250, 250)
        self.star_color_cool = (220, 225, 235)
        self.star_color_warm = (235, 230, 215)
        self.star_color_dim = (180, 185, 195)

        self.generate_stars()

    def get_star_sm(self, color):
        star_surf = pygame.Surface((self.sm_px, self.sm_px), pygame.SRCALPHA)
        pygame.draw.rect(
            star_surf,
            color,
            (
                0,
                0,
                self.sm_px,
                self.sm_px
            )
        )
        return star_surf
    
    def generate_stars(self):
        width = self.screen.get_width()
        height = self.screen.get_height()

        # top-left quadrant
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.03, height*0.08))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.07, height*0.22))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.11, height*0.05))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.16, height*0.33))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.20, height*0.14))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.24, height*0.41))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.28, height*0.07))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.31, height*0.27))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.35, height*0.46))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.38, height*0.17))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.42, height*0.38))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.45, height*0.09))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.09, height*0.39))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.14, height*0.18))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.19, height*0.44))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.22, height*0.29))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.36, height*0.30))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.40, height*0.24))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.44, height*0.48))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.06, height*0.31))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.13, height*0.47))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.30, height*0.35))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.37, height*0.04))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.48, height*0.20))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.25, height*0.48))

        # top-right quadrant
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.52, height*0.11))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.56, height*0.26))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.60, height*0.06))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.64, height*0.39))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.68, height*0.17))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.72, height*0.44))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.75, height*0.08))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.79, height*0.31))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.83, height*0.48))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.87, height*0.21))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.91, height*0.36))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.95, height*0.13))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.54, height*0.42))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.59, height*0.19))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.63, height*0.46))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.67, height*0.03))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.70, height*0.34))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.76, height*0.14))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.80, height*0.41))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.84, height*0.07))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.89, height*0.28))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.93, height*0.46))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.97, height*0.18))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.73, height*0.22))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.58, height*0.33))

        # bottom-left quadrant
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.04, height*0.56))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.09, height*0.69))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.14, height*0.53))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.18, height*0.82))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.22, height*0.63))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.26, height*0.74))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.30, height*0.57))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.34, height*0.88))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.38, height*0.65))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.42, height*0.79))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.46, height*0.54))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.49, height*0.93))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.07, height*0.77))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.12, height*0.61))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.17, height*0.91))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.21, height*0.68))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.25, height*0.52))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.29, height*0.86))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.36, height*0.71))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.41, height*0.97))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.45, height*0.60))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.02, height*0.84))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.33, height*0.58))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.48, height*0.76))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.15, height*0.72))

        # bottom-right quadrant
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.53, height*0.58))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.57, height*0.71))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.61, height*0.54))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.65, height*0.85))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.69, height*0.64))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.73, height*0.76))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.77, height*0.59))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.81, height*0.91))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.85, height*0.67))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.89, height*0.80))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.93, height*0.55))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.97, height*0.73))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.55, height*0.89))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.59, height*0.62))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.63, height*0.94))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.67, height*0.51))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.71, height*0.83))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.75, height*0.70))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.79, height*0.57))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.83, height*0.78))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.88, height*0.96))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*0.92, height*0.63))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*0.96, height*0.87))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*0.51, height*0.75))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*0.74, height*0.53))

        # --- second screen section ---
        # top-left
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.04, height*0.11))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.08, height*0.27))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.13, height*0.06))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.17, height*0.38))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.21, height*0.19))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.25, height*0.43))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.29, height*0.09))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.33, height*0.31))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.37, height*0.49))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.40, height*0.14))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.44, height*0.35))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.47, height*0.04))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.10, height*0.42))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.15, height*0.22))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.24, height*0.16))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.28, height*0.37))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.35, height*0.26))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.41, height*0.45))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.06, height*0.33))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.31, height*0.07))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.46, height*0.18))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.49, height*0.24))
        # top-right
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.53, height*0.08))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.57, height*0.23))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.61, height*0.05))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.66, height*0.37))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.70, height*0.16))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.74, height*0.45))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.78, height*0.10))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.82, height*0.29))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.86, height*0.42))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.90, height*0.19))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.94, height*0.33))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.97, height*0.07))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.52, height*0.46))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.58, height*0.34))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.62, height*0.14))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.67, height*0.48))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.71, height*0.25))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.75, height*0.38))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.80, height*0.12))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.89, height*0.27))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.65, height*0.30))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.79, height*0.04))
        # bottom-left
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.03, height*0.57))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.07, height*0.71))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.12, height*0.54))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.16, height*0.83))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.20, height*0.65))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.24, height*0.76))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.28, height*0.58))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.32, height*0.90))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.36, height*0.67))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.40, height*0.81))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.44, height*0.55))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.48, height*0.94))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.09, height*0.78))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.14, height*0.63))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.22, height*0.70))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.27, height*0.53))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.34, height*0.87))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.39, height*0.72))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.43, height*0.98))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.05, height*0.85))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.26, height*0.61))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.46, height*0.60))
        # bottom-right
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.52, height*0.60))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.56, height*0.74))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.60, height*0.55))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.65, height*0.87))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.69, height*0.65))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.73, height*0.78))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.77, height*0.60))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.81, height*0.93))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.85, height*0.69))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.89, height*0.82))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.93, height*0.57))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.97, height*0.75))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.54, height*0.91))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.59, height*0.63))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*1.63, height*0.96))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.68, height*0.52))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.72, height*0.85))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.76, height*0.71))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*1.83, height*0.79))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.88, height*0.98))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*1.62, height*0.68))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*1.78, height*0.53))

        # --- third screen section ---
        # top-left
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.02, height*0.14))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.06, height*0.29))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.11, height*0.07))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.15, height*0.41))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.20, height*0.18))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.24, height*0.35))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.28, height*0.04))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.32, height*0.26))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.37, height*0.47))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.41, height*0.12))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.45, height*0.38))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.48, height*0.22))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.08, height*0.44))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.13, height*0.16))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.22, height*0.09))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.27, height*0.32))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.34, height*0.48))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.39, height*0.21))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.05, height*0.31))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.16, height*0.03))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.43, height*0.46))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.49, height*0.08))
        # top-right
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.52, height*0.10))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.57, height*0.25))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.61, height*0.06))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.65, height*0.39))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.70, height*0.15))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.74, height*0.44))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.78, height*0.08))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.83, height*0.31))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.87, height*0.46))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.91, height*0.20))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.95, height*0.35))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.98, height*0.11))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.54, height*0.48))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.59, height*0.32))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.63, height*0.17))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.68, height*0.43))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.72, height*0.27))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.76, height*0.36))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.81, height*0.13))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.90, height*0.24))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.56, height*0.19))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.80, height*0.38))
        # bottom-left
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.03, height*0.55))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.07, height*0.68))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.12, height*0.53))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.16, height*0.80))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.20, height*0.62))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.24, height*0.74))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.29, height*0.56))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.33, height*0.89))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.37, height*0.65))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.41, height*0.78))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.45, height*0.52))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.48, height*0.93))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.09, height*0.76))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.13, height*0.61))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.22, height*0.68))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.27, height*0.84))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.34, height*0.57))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.38, height*0.73))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.43, height*0.97))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.05, height*0.84))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.26, height*0.60))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.46, height*0.58))
        # bottom-right
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.51, height*0.59))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.55, height*0.73))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.60, height*0.54))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.64, height*0.86))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.68, height*0.64))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.72, height*0.77))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.77, height*0.59))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.81, height*0.92))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.85, height*0.68))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.89, height*0.81))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.93, height*0.56))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.97, height*0.74))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.53, height*0.90))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.58, height*0.62))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_bright), (width*2.63, height*0.95))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.67, height*0.51))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.71, height*0.83))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.75, height*0.70))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_cool),   (width*2.83, height*0.79))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.88, height*0.97))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_warm),   (width*2.62, height*0.67))
        self.star_bg_surf.blit(self.get_star_sm(self.star_color_dim),    (width*2.77, height*0.52))

    def draw(self, camera_x, camera_y):
        pos_offset = (camera_x // 4) % self.star_bg_width
        self.screen.blit(self.star_bg_surf, (-pos_offset, 0))
        if pos_offset + self.screen.get_width() > self.star_bg_width:
            self.screen.blit(self.star_bg_surf, (-pos_offset + self.star_bg_width, 0))
